### ISSUE TITLE
Admission-webhook failed to start service Error: open /etc/webhook/certs/cert.pem: no such file or directory

### ISSUE THREAD

**Issue by alekseytivonchik** [canonical/admission-webhook-operator#126]
### Bug Description

when creating a Notebook, I get the error:
`statefulset/tst-note-t: create Pod tst-note-t-0 in StatefulSet tst-note-t failed error: Internal error occurred: failed calling webhook "admission-webhook.kubeflow.org": failed to call webhook: Post "https://admission-webhook.kubeflow.svc:4443/apply-poddefault?timeout=10s": dial tcp 10.233.59.161:4443: connect: connection refused`
<img width="1497" alt="Снимок экрана 2024-02-13 в 15 28 37" src="https://github.com/canonical/bundle-kubeflow/assets/26677726/da9d32f1-01d5-4c19-ba44-1e721bdd54d4">

### To Reproduce

snap install juju
juju bootstrap my-k8s
juju add-model kubeflow
juju deploy kubeflow --trust

### Environment

K8s: v1.28.6
OS: Ubuntu 22.04
Juju: 3.3.1-genericlinux-amd64

admission-webhook: 1.8/stable
argo-controller: 3.3.10/stable
dex-auth: 2.36/stable
envoy: 2.0/stable
istio-ingressgateway: 1.17/stable
istio-pilot: 1.17/stable
jupyter-controller: 1.8/stable
jupyter-ui: 1.8/stable
katib-controller: 0.16/stable
katib-db: 8.0/stable
katib-db-manager: 0.16/stable
katib-ui: 0.16/stable
kfp-api: 2.0/stable
kfp-db: 8.0/stable
kfp-metadata-writer: 2.0/stable
kfp-persistence: 2.0/stable
kfp-profile-controller: 2.0/stable
kfp-schedwf: 2.0/stable
kfp-ui: 2.0/stable
kfp-viewer: 2.0/stable
kfp-viz: 2.0/stable
knative-eventing: 1.10/stable
knative-operator: 1.10/stable
knative-serving: 1.10/stable
kserve-controller: 0.11/stable
kubeflow-dashboard: 1.8/stable
kubeflow-profiles: 1.8/stable
kubeflow-roles: 1.8/stable
kubeflow-volumes: 1.8/stable
metacontroller-operator: 3.0/stable
minio: ckf-1.8/stable
mlmd: 1.14/stable
oidc-gatekeeper: ckf-1.8/stable
pvcviewer-operator: 1.8/stable
seldon-controller-manager: 1.17/stable
tensorboard-controller: 1.8/stable
tensorboards-web-app: 1.8/stable
training-operator: 1.7/stable

### Relevant Log Output
```
Unit                          Workload     Agent  Address         Ports          Message
admission-webhook/0*          maintenance  idle   10.233.118.141                 Workload failed health check
```
```shell
kubectl logs admission-webhook-0 -n kubeflow
<info messages...>
2024-02-13T11:53:36.729Z [container-agent] 2024-02-13 11:53:36 ERROR juju-log Traceback (most recent call last):
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/charmed_kubeflow_chisme/pebble/_update_layer.py", line 31, in update_layer
2024-02-13T11:53:36.729Z [container-agent]     container.replan()
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/model.py", line 1915, in replan
2024-02-13T11:53:36.729Z [container-agent]     self._pebble.replan_services()
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/pebble.py", line 1680, in replan_services
2024-02-13T11:53:36.729Z [container-agent]     return self._services_action('replan', [], timeout, delay)
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/pebble.py", line 1761, in _services_action
2024-02-13T11:53:36.729Z [container-agent]     raise ChangeError(change.err, change)
2024-02-13T11:53:36.729Z [container-agent] ops.pebble.ChangeError: cannot perform the following tasks:
2024-02-13T11:53:36.729Z [container-agent] - Start service "admission-webhook" (cannot start service: exited quickly with code 255)
2024-02-13T11:53:36.729Z [container-agent] ----- Logs from task 0 -----
2024-02-13T11:53:36.729Z [container-agent] 2024-02-13T11:53:36Z INFO Most recent service output:
2024-02-13T11:53:36.729Z [container-agent]     F0213 11:53:36.706006      14 config.go:46] config=main.Config{CertFile:"/etc/webhook/certs/cert.pem", KeyFile:"/etc/webhook/certs/key.pem"} Error: open /etc/webhook/certs/cert.pem: no such file or directory
2024-02-13T11:53:36.729Z [container-agent] 2024-02-13T11:53:36Z ERROR cannot start service: exited quickly with code 255
<...info messages>
```

**Comment by NohaIhab** [comment]
the fix #125 is now merged and promoted to `1.8/stable`
You can now refresh your charms, for reference the new revision is `301`.
cc: @natalytvinova @Barteus @alekseytivonchik
